markdown: kramdown
highlighter: rouge
paginate: 10
language: en-us
lang: en_US
future: true
baseurl: /
title: Faast
description: The official Faast Community Blog
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
production_url: 'https://faastblog.com'
source_url: 'https://github.com/FaastBlog/faast'
navigation: true
subscribers: true
twitter: faastblog
facebook: faastblog
disqus: true
disqus_shortname: faastblog
google_analytics: UA-122678344-1
permalink: '/:title'
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-admin
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-workbox-plugin
url: 'https://www.faastblog.com'
defaults:
  - scope:
      path: /google7602a4aeab5cf1dc.html
    values:
      sitemap: false
feed:
  path: feed.xml
safe: false
lsi: false
pwa:
  sw_src_filepath: service-worker.js
  sw_dest_filename: service-worker.js
  dest_js_directory: assets/js
  precache_recent_posts_num: 6
  precache_glob_directory: /
username: FaastBlog
repo: faast
branch: master
relative_source: ../site/
destination: ../site/
exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - '*.Rmd'
  - .git*
